"""PasswordType on User.passhash field.

Revision ID: 28dd231a45a9
Revises: a3507404bc1
Create Date: 2014-06-05 19:58:00.076788

"""

# revision identifiers, used by Alembic.
revision = '28dd231a45a9'
down_revision = 'a3507404bc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'passhash', type_=sa.String(length=64),
                    nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'passhash', type_=sa.String(length=255),
                    nullable=False)
    ### end Alembic commands ###
