"""Target rename field and relation with TargetType

Revision ID: 597bf4cfb0ca
Revises: 275c63c374b0
Create Date: 2014-06-19 16:13:46.078014

"""

# revision identifiers, used by Alembic.
revision = '597bf4cfb0ca'
down_revision = '275c63c374b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('target_type_id', sa.Integer(), nullable=False))
    op.drop_column('target', 'target_type')
    ### end Alembic commands ###
    op.create_foreign_key('fk_target_target_type', 'target', 'target_type',
                          ['target_type_id'], ['id'])


def downgrade():
    op.drop_constraint('fk_target_target_type', 'target', type_='foreignkey')
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('target_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('target', 'target_type_id')
    ### end Alembic commands ###
