"""Add AuditLog model.

Revision ID: a3507404bc1
Revises: 2593545089e4
Create Date: 2014-06-05 16:39:55.468563

"""

# revision identifiers, used by Alembic.
revision = 'a3507404bc1'
down_revision = '2593545089e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_dt', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=45), nullable=False),
    sa.Column('object_type', sa.String(length=45), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditlog')
    ### end Alembic commands ###
